apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: symbiosis-ingress
  annotations:
    kubernetes.io/ingress.class: public
spec:
  ingressClassName: public
  
  rules:
  - host: symbiosis.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: symbiosis-svc
            port:
              number: 3000
