apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: superadminroot
  MYSQL_USER:      symuser
  MYSQL_PASSWORD:  symuserpass
  MYSQL_DATABASE:  test
